### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by bamtang-dev** [SasLuca/rayfork#34]
I'd like the idea of raylib for iOS and consoles
sad

**Comment by jtaart** [comment]
I believe SasLuca has become to busy to work on this, but there is hope that iOS may come to raylib in the future. raylib 5.0 has just made it easier to add new platforms, from my understanding. The Nintendo Switch has already been added recently.

**Comment by SasLuca** [comment]
Pretty much sadly, i began work on a startup and never got back to rayfork due to lack of time.

Maybe porting the original raylib to iOS is a better use of mine and other people's time than the big reimagining I ended up pursuing with rayfork.

I also think rayfork would make more sense as a native zig library because most of its features are native to zig (eg: allocator awareness).

**Comment by bamtang-dev** [comment]
thanks for the answer!

**Comment by truedat101** [comment]
@bamtang-dev I am taking a look at the metal port for apple devices, since the default is GL and that builds but isn't supported.  I haven't scoped the effort but I am interested in this as well, generally, raylib style is useful for making quick interfaces and prototypes as well.  

Will make a fork of this.  Trying to figure out the pieces.  I did a bit of experimentation on Raymob (https://github.com/Bigfoot71/RayMob) on the android side but I really would like to get some iOS stuff going.  This project works pretty well but reviewing the code, the author didn't implement 100% of the api calls and made some assumptions about things that may not be true.  For example, didn't implement things to interrogate the screen size or number of screens.  It's actually possible on Android to have more than one screen (now) via either a second screen on the device or external displays, supported on Samsung devices.

**Comment by bamtang-dev** [comment]
@truedat101 would be great!

**Comment by truedat101** [comment]
Cool, I am getting my head around the build and will continue on the fork for the fork.
